# Test case for Kubernetes 1.34+ short Docker image name blocking behavior
# This demonstrates the difference between CRI-O and containerd runtimes
# K8s 1.34+ blocks short image names like "nginx:latest" for security

apiVersion: v1
kind: Namespace
metadata:
  name: image-name-blocking-test
---
# Test Pod 1: Short image name that should be blocked in K8s 1.34+
apiVersion: v1
kind: Pod
metadata:
  name: test-short-image-name-blocked
  namespace: image-name-blocking-test
  labels:
    test: short-image-blocking
spec:
  restartPolicy: Never
  containers:
  - name: nginx-short
    image: nginx:latest  # This should be blocked in K8s 1.34+ with CRI-O
    command: 
    - /bin/sh
    - -c
    - |
      echo "If you see this, short image names are allowed"
      nginx -v
      echo "Short image name test completed"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
---
# Test Pod 2: Full image name that should work
apiVersion: v1
kind: Pod
metadata:
  name: test-full-image-name-allowed
  namespace: image-name-blocking-test
  labels:
    test: full-image-allowed
spec:
  restartPolicy: Never
  containers:
  - name: nginx-full
    image: docker.io/library/nginx:latest  # This should always work
    command:
    - /bin/sh
    - -c
    - |
      echo "Full image name working correctly"
      nginx -v
      echo "Full image name test completed"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
---
# Test Pod 3: Another short image name example
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-short-blocked
  namespace: image-name-blocking-test
  labels:
    test: short-image-blocking
spec:
  restartPolicy: Never
  containers:
  - name: alpine-short
    image: alpine:latest  # This should be blocked in K8s 1.34+ with CRI-O
    command: 
    - /bin/sh
    - -c
    - |
      echo "If you see this, short image names are allowed"
      cat /etc/alpine-release
      echo "Alpine short image name test completed"
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
---
# Test Pod 4: Full alpine image name that should work
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-full-allowed
  namespace: image-name-blocking-test
  labels:
    test: full-image-allowed
spec:
  restartPolicy: Never
  containers:
  - name: alpine-full
    image: docker.io/library/alpine:latest  # This should always work
    command:
    - /bin/sh
    - -c
    - |
      echo "Full alpine image name working correctly"
      cat /etc/alpine-release
      echo "Alpine full image name test completed"
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
---
# Job to validate image name blocking behavior
apiVersion: batch/v1
kind: Job
metadata:
  name: image-name-blocking-validation
  namespace: image-name-blocking-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: validator
        image: docker.io/library/alpine:latest  # Using full name for compatibility
        command:
        - /bin/sh
        - -c
        - |
          echo "=== Docker Image Name Blocking Validation Test ==="
          echo "Kubernetes Version: $(wget -qO- --no-check-certificate https://kubernetes.default.svc/version 2>/dev/null | grep gitVersion || echo 'Unknown')"
          echo "Container Runtime: $(cat /proc/1/cgroup | grep -o 'cri-o\|containerd' | head -1 || echo 'Unknown')"
          echo ""
          
          echo "=== Test Summary ==="
          echo "In Kubernetes 1.34+ with CRI-O:"
          echo "  ❌ Short names like 'nginx:latest' should be BLOCKED"
          echo "  ✅ Full names like 'docker.io/library/nginx:latest' should WORK"
          echo ""
          echo "In Kubernetes 1.34+ with containerd:"
          echo "  ⚠️  Short names may still be allowed (inconsistent behavior)"
          echo "  ✅ Full names should always work"
          echo ""
          echo "This demonstrates why CRI-O testing is important for K8s 1.34+ security features"
          echo ""
          echo "To test manually:"
          echo "1. Try: kubectl run test-short --image=nginx:latest"
          echo "2. Try: kubectl run test-full --image=docker.io/library/nginx:latest"
          echo "3. With CRI-O in K8s 1.34+: #1 should fail, #2 should work"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"